# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 百度贴吧自动签到吧

on:
  schedule:
  - cron: '53 9 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout # 拉取master分支
      uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Sign In
      env:
        COOKIE: ${{secrets.COOKIE}}
        DINGTALK_SECRET: ${{secrets.DINGTALK_SECRET}}
        DINGTALK_WEBHOOK: ${{secrets.DINGTALK_WEBHOOK}}
      run: |
          python main.py


